services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/nextjs
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    command: npm start
